[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
titan_zk_vault = "52an8WjtfxpkCqZZ1AYFkaDTGb4RyNFFD9VQRVdxcpJw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/titan_zk_vault"]
