"""
logic/sage/gatekeeper.py
Implements the Advantage-Based Hybrid Execution Routing for Titan V1.4.

V2.0 Step 5 Update: Adds STATE_NEED_RESEARCH as a formal 4th routing mode.
When the Titan's confidence is low (A ≤ 0.4 / Shadow) AND the prompt requests
real-time or current-world information, the Gatekeeper escalates to STATE_NEED_RESEARCH
so the Stealth-Sage research pipeline is invoked before calling the LLM.
"""
import torch
import torch.nn.functional as F
from tensordict import TensorDict

class SageGatekeeper:
    """
    The Titan's "Ego" layer. Decides execution mode based on the Scholar's Confidence (Advantage).
    Routes between Sovereign (Autonomous), Collaborative (LLM-Assisted), and Shadow (Oracle/LLM governed).
    This acts as the final decision hub before executing the user prompt loop.
    """
    def __init__(self, scholar_instance, recorder_instance):
        """
        Initializes the Gatekeeper with external cognitive hooks.

        Args:
            scholar_instance (SageScholar): Reference to the Scholar to access the Neural Networks (A, Q, V).
            recorder_instance (SageRecorder): Reference to the central data hub for KNN history decoding.
        """
        self.scholar = scholar_instance
        self.recorder = recorder_instance
        self.similarity_floor = 0.60
        self._decision_history: list[str] = []
        self._max_history = 100

    @property
    def sovereignty_score(self) -> float:
        """Rolling sovereignty percentage (0-100)."""
        if not self._decision_history:
            return 0.0
        credits = sum(
            1.0 if d == "sovereign" else 0.5 if d == "collaborative" else 0.0
            for d in self._decision_history
        )
        return (credits / len(self._decision_history)) * 100

    def _record_decision(self, mode: str):
        """Called after each gatekeeper routing decision."""
        self._decision_history.append(mode)
        if len(self._decision_history) > self._max_history:
            self._decision_history.pop(0)

    def find_grounded_action(self, a_raw: torch.Tensor) -> tuple[torch.Tensor, str]:
        """
        KNN Decoder: To prevent neural hallucinations, it semantic matches the Actor's raw continuous 
        thought output (`a_raw`) against purely historical actions that resulted in a positive reward.
        Enforces a stringent cosine similarity floor (0.85) to ensure execution fidelity.
        
        Args:
            a_raw (torch.Tensor): The 128-dim ungrounded action vector generated by the Actor Policy.
            
        Returns:
            tuple[torch.Tensor, str]: The matched historical tensor (`a_historical`) and its decoded exact text intent.
                                      Returns (None, "") if the nearest match fails the similarity floor.
        """
        # Ensure we have history
        if len(self.recorder.storage) == 0:
            return None, ""
            
        best_similarity = -1.0
        best_vector = None
        best_text = ""
        
        # In a production environment this would be an indexed DB (e.g., FAISS).
        # PyTorch looping for simplicity/MVP.
        for transition in self.recorder.storage:
            reward = transition.get("reward").item()
            if reward > 0:
                a_hist = transition.get("action_intent_vector")
                # Flatten for cosine similarity
                sim = F.cosine_similarity(a_raw.view(1, -1), a_hist.view(1, -1)).item()
                if sim > best_similarity:
                    best_similarity = sim
                    best_vector = a_hist
                    
                    # Extract string from action_text_bytes (may be None for older transitions)
                    raw_bytes = transition.get("action_text_bytes")
                    if raw_bytes is not None:
                        action_bytes_padded = raw_bytes.flatten().tolist()
                        action_bytes_clean = bytes([int(b) for b in action_bytes_padded if b != 0])
                        best_text = action_bytes_clean.decode('utf-8', errors='ignore')
        
        # If we failed the floor, we reject the grounding
        if best_similarity < self.similarity_floor:
            return None, ""
            
        return best_vector, best_text

    def _is_informational_query(self, prompt: str) -> bool:
        """
        Detects whether a prompt requires real-world, real-time, or current-event data
        that the Titan's static memory cannot answer reliably.

        This acts as the "Uncertainty Marker" filter — it distinguishes between
        prompts like "write me a poem" (Shadow, LLM handles) and prompts like
        "what is the SOL price today" (STATE_NEED_RESEARCH, Stealth-Sage handles).

        The check is case-insensitive and evaluates a curated set of keywords that
        strongly correlate with a need for live, external data.

        Args:
            prompt (str): The raw user prompt string.

        Returns:
            bool: True if the prompt requires research; False if it can be handled
                  by the LLM from static memory alone.
        """
        _INFORMATIONAL_KEYWORDS = {
            # Time-sensitive data
            "latest", "current", "today", "right now", "right now",
            "recent", "news", "price", "predict", "forecast",
            # Market / financial signals
            "market", "sol price", "bitcoin price", "eth price",
            "token price", "trading", "apy", "yield", "tvl",
            # Social pulse
            "trending", "people saying", "sentiment",
            "what does", "what do people", "community",
            # Event-driven
            "just happened", "breaking", "announcement", "launch",
            "update", "release", "upgrade",
        }
        lower = prompt.lower()
        return any(kw in lower for kw in _INFORMATIONAL_KEYWORDS)

    def decide_execution_mode(
        self, state_tensor: torch.Tensor, raw_prompt: str = ""
    ) -> tuple[str, float, str]:
        """
        Core logic hub for Titan V1.4 / V2.0. Routes execution flow by grounding the
        thought, verifying confidence through the Advantage Function (A = Q - V),
        and assigning a routing mode.

        V2.0 Step 5 adds STATE_NEED_RESEARCH as a 4th mode:
        - After determining Shadow mode (A ≤ 0.4), the Gatekeeper checks whether
          the raw prompt signals a need for real-world data via _is_informational_query().
          If yes, STATE_NEED_RESEARCH is returned so the Stealth-Sage pipeline fires
          before the LLM is invoked.

        Modes:
            - Sovereign (A > 0.8): The agent handles the task entirely autonomously.
            - Collaborative (0.4 < A ≤ 0.8): The agent suggests an action for the LLM.
            - Shadow (A ≤ 0.4): The agent fully defers to the LLM Oracle.
            - STATE_NEED_RESEARCH (A ≤ 0.4 + informational query): Research first.

        Args:
            state_tensor (torch.Tensor): The 128-dim representation of the user's prompt.
            raw_prompt (str): The original user prompt string (used for informational
                              query detection). Defaults to "" for backward compatibility.

        Returns:
            tuple[str, float, str]: (Mode String, Calculated Advantage Float, Decoded Action String)
        """
        # 1. Generate Raw Thought
        with torch.no_grad():
            td = TensorDict({"observation": state_tensor.unsqueeze(0)}, batch_size=[1])
            self.scholar.actor_module(td)
            a_raw = td["action"].squeeze(0)
            
        # 2. Ground the Thought (KNN Decoder)
        a_hist, decoded_text = self.find_grounded_action(a_raw)
        
        # 3. Calculate Advantage if Grounded
        if a_hist is None:
            self._record_decision("shadow")
            return "Shadow", 0.0, ""
            
        with torch.no_grad():
            # Concat State + Action for Q-Net
            td_q = TensorDict({
                "observation": state_tensor.unsqueeze(0),
                "action": a_hist.unsqueeze(0)
            }, batch_size=[1])
            self.scholar.qvalue_module(td_q)
            q_val = td_q["state_action_value"].item()
            
            td_v = TensorDict({"observation": state_tensor.unsqueeze(0)}, batch_size=[1])
            self.scholar.value_module(td_v)
            v_val = td_v["state_value"].item()
            
        advantage = q_val - v_val

        # 4. Route
        if advantage > 0.65:
            self._record_decision("sovereign")
            return "Sovereign", advantage, decoded_text
        elif advantage > 0.25:
            self._record_decision("collaborative")
            return "Collaborative", advantage, decoded_text
        else:
            # Shadow: low confidence. Check if real-world data is needed.
            if raw_prompt and self._is_informational_query(raw_prompt):
                self._record_decision("research")
                return "STATE_NEED_RESEARCH", advantage, ""
            self._record_decision("shadow")
            return "Shadow", advantage, ""
