#!/usr/bin/env python3
"""
Setup script for Titan Observatory frontend deployment.
Configures nginx reverse proxy, HTTPS (Let's Encrypt), and auth settings.

Usage:
    python scripts/setup_frontend.py              # Interactive setup
    python scripts/setup_frontend.py --dev         # Dev mode (localhost only)
    python scripts/setup_frontend.py --domain example.com  # Production with domain
"""

import argparse
import os
import subprocess
import sys
from pathlib import Path
from textwrap import dedent

PROJECT_ROOT = Path(__file__).resolve().parent.parent
NGINX_OUTPUT_DIR = PROJECT_ROOT / "data" / "nginx"
NGINX_CONF_NAME = "titan.conf"


def generate_nginx_config(
    domain: str,
    frontend_port: int = 3000,
    api_port: int = 7777,
    ssl: bool = False,
    rate_limit_rps: int = 10,
) -> str:
    """Generate a production-grade nginx config for Titan Observatory."""

    server_name = domain if domain != "localhost" else "_"
    ssl_block = ""
    listen_block = "listen 80;"

    if ssl and domain != "localhost":
        listen_block = dedent(f"""\
            listen 443 ssl http2;
            listen [::]:443 ssl http2;
            ssl_certificate /etc/letsencrypt/live/{domain}/fullchain.pem;
            ssl_certificate_key /etc/letsencrypt/live/{domain}/privkey.pem;
            ssl_protocols TLSv1.2 TLSv1.3;
            ssl_ciphers HIGH:!aNULL:!MD5;
            ssl_prefer_server_ciphers on;
            ssl_session_cache shared:SSL:10m;
            ssl_session_timeout 10m;""")

        ssl_block = dedent(f"""\
        # HTTP -> HTTPS redirect
        server {{
            listen 80;
            listen [::]:80;
            server_name {domain};

            location /.well-known/acme-challenge/ {{
                root /var/www/certbot;
            }}

            location / {{
                return 301 https://$host$request_uri;
            }}
        }}
        """)

    config = dedent(f"""\
    # Titan Observatory — nginx reverse proxy
    # Generated by scripts/setup_frontend.py
    # Domain: {domain}

    # Rate limiting zone: {rate_limit_rps} req/s per IP
    limit_req_zone $binary_remote_addr zone=titan_limit:10m rate={rate_limit_rps}r/s;
    limit_req_zone $binary_remote_addr zone=titan_chat:10m rate=2r/s;

    # Upstream definitions
    upstream titan_frontend {{
        server 127.0.0.1:{frontend_port};
    }}

    upstream titan_api {{
        server 127.0.0.1:{api_port};
    }}

    {ssl_block}server {{
        {listen_block}
        server_name {server_name};

        # Security headers
        add_header X-Frame-Options "SAMEORIGIN" always;
        add_header X-Content-Type-Options "nosniff" always;
        add_header X-XSS-Protection "1; mode=block" always;
        add_header Referrer-Policy "strict-origin-when-cross-origin" always;
        add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com; img-src 'self' data: blob: https:; connect-src 'self' ws: wss: https:; frame-ancestors 'self';" always;
        add_header Permissions-Policy "camera=(), microphone=(), geolocation=()" always;

        # Gzip compression
        gzip on;
        gzip_types text/plain text/css application/json application/javascript text/xml application/xml text/javascript;
        gzip_min_length 256;

        # Frontend — Next.js
        location / {{
            limit_req zone=titan_limit burst=20 nodelay;

            proxy_pass http://titan_frontend;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }}

        # API — Titan Observatory backend
        location /api/ {{
            limit_req zone=titan_limit burst=30 nodelay;

            # Strip /api prefix and proxy to port {api_port}
            rewrite ^/api/(.*) /$1 break;
            proxy_pass http://titan_api;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # SSE support (for /chat/stream)
            proxy_buffering off;
            proxy_cache off;
            proxy_read_timeout 120s;
        }}

        # Chat endpoint — stricter rate limit
        location /api/chat {{
            limit_req zone=titan_chat burst=5 nodelay;

            rewrite ^/api/(.*) /$1 break;
            proxy_pass http://titan_api;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_buffering off;
            proxy_cache off;
            proxy_read_timeout 120s;
        }}

        # WebSocket endpoint
        location /ws {{
            proxy_pass http://titan_api;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_read_timeout 86400s;
            proxy_send_timeout 86400s;
        }}

        # Static assets — long cache
        location /_next/static/ {{
            proxy_pass http://titan_frontend;
            proxy_cache_valid 200 365d;
            add_header Cache-Control "public, max-age=31536000, immutable";
        }}

        # Health check (no rate limit)
        location = /api/health {{
            rewrite ^/api/(.*) /$1 break;
            proxy_pass http://titan_api;
        }}

        # Block dotfiles
        location ~ /\\. {{
            deny all;
            return 404;
        }}

        # Request size limit
        client_max_body_size 1m;
    }}
    """)

    return config


def install_certbot(domain: str) -> bool:
    """Attempt to obtain SSL certificate via certbot."""
    print(f"\n[HTTPS] Requesting Let's Encrypt certificate for {domain}...")
    try:
        subprocess.run(
            [
                "sudo", "certbot", "certonly", "--nginx",
                "-d", domain,
                "--non-interactive",
                "--agree-tos",
                "--email", f"admin@{domain}",
            ],
            check=True,
        )
        print(f"[HTTPS] Certificate obtained for {domain}")
        return True
    except FileNotFoundError:
        print("[HTTPS] certbot not found. Install with: sudo apt install certbot python3-certbot-nginx")
        return False
    except subprocess.CalledProcessError as e:
        print(f"[HTTPS] certbot failed: {e}")
        return False


def main():
    parser = argparse.ArgumentParser(
        description="Setup Titan Observatory frontend deployment (nginx + HTTPS)"
    )
    parser.add_argument("--dev", action="store_true", help="Dev mode (localhost, no SSL)")
    parser.add_argument("--domain", type=str, help="Production domain (enables HTTPS)")
    parser.add_argument("--frontend-port", type=int, default=3000, help="Next.js port (default: 3000)")
    parser.add_argument("--api-port", type=int, default=7777, help="Titan API port (default: 7777)")
    parser.add_argument("--rate-limit", type=int, default=10, help="Requests/second per IP (default: 10)")
    parser.add_argument("--no-ssl", action="store_true", help="Skip SSL even with --domain")
    args = parser.parse_args()

    # Determine mode
    if args.dev:
        domain = "localhost"
        ssl = False
        print("[MODE] Development — localhost only, no SSL")
    elif args.domain:
        domain = args.domain
        ssl = not args.no_ssl
        print(f"[MODE] Production — domain: {domain}, SSL: {'yes' if ssl else 'no'}")
    else:
        # Interactive
        print("=" * 60)
        print("  Titan Observatory — Frontend Deployment Setup")
        print("=" * 60)
        print()
        domain = input("Domain (or 'localhost' for dev): ").strip() or "localhost"
        ssl = False
        if domain != "localhost":
            ssl_input = input("Enable HTTPS via Let's Encrypt? [Y/n]: ").strip().lower()
            ssl = ssl_input != "n"

    # Generate config
    config = generate_nginx_config(
        domain=domain,
        frontend_port=args.frontend_port,
        api_port=args.api_port,
        ssl=ssl,
        rate_limit_rps=args.rate_limit,
    )

    # Write config
    NGINX_OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    conf_path = NGINX_OUTPUT_DIR / NGINX_CONF_NAME
    conf_path.write_text(config)
    print(f"\n[NGINX] Config written to: {conf_path}")

    # SSL certificate
    if ssl and domain != "localhost":
        install_certbot(domain)

    # Instructions
    print()
    print("=" * 60)
    print("  Next Steps")
    print("=" * 60)
    print()
    print("1. Install nginx (if not already):")
    print("   sudo apt install nginx")
    print()
    print("2. Link the config:")
    print(f"   sudo ln -sf {conf_path.resolve()} /etc/nginx/sites-enabled/{NGINX_CONF_NAME}")
    print()
    print("3. Remove default site (if needed):")
    print("   sudo rm -f /etc/nginx/sites-enabled/default")
    print()
    print("4. Test and reload nginx:")
    print("   sudo nginx -t && sudo systemctl reload nginx")
    print()
    print("5. Start the services:")
    print(f"   # Frontend (port {args.frontend_port}):")
    print(f"   cd {PROJECT_ROOT / 'titan-observatory'} && npm run build && npm start")
    print(f"   # API (port {args.api_port}):")
    print("   # Start via your Titan plugin / titan_main.py")
    print()

    if ssl:
        print("6. Auto-renewal is configured via certbot systemd timer.")
        print("   Verify with: sudo systemctl status certbot.timer")
        print()

    if domain != "localhost":
        print(f"Access: {'https' if ssl else 'http'}://{domain}")
    else:
        print("Access: http://localhost")
    print()


if __name__ == "__main__":
    main()
