"""Phase 7 — systemd install + first start + health gate (W1.e).

Mirrors the fleet's `titan-tN.service` (a system-level unit owned by the
installing user) but generalized to the tester's install root + resolved
titan_id. Survives reboot (system unit, `WantedBy=multi-user.target`) without
needing `loginctl enable-linger`.

Steps:
  1. Resolve titan_id (data/titan_identity.json → fallback "T1", matching
     state_registry.resolve_titan_id) + the installing user + paths.
  2. Verify the kernel binary + identity keypair exist (the unit's ExecStart
     target + ConditionPathExists). Missing binary → fail with remediation;
     missing keypair → warn (the unit installs but won't start until genesis).
  3. Render `titan.service` and the generic ExecStartPre/ExecStopPost cleanup.
  4. Install with an EXPLICIT, MINIMAL sudo footprint — every privileged
     command is printed before it runs (RFP: "print exactly what runs as root").
  5. `daemon-reload` + `enable --now`.
  6. Health-gate: poll http://127.0.0.1:<api_port>/health for HTTP 200, up to
     5 minutes (RFP W1.e).

Stdlib-only (urllib for the health probe) — runs on the system interpreter.
"""
from __future__ import annotations

import getpass
import json
import re
import subprocess
import time
import urllib.error
import urllib.request
from pathlib import Path

from .modes import Mode
from .preflight import Result
from .ui import cprint

UNIT_NAME = "titan.service"
UNIT_DEST = Path("/etc/systemd/system") / UNIT_NAME
DEFAULT_API_PORT = 7777
HEALTH_TIMEOUT_S = 300      # RFP W1.e — 5-minute first-start health gate
HEALTH_INTERVAL_S = 5


# ── id / path resolution ────────────────────────────────────────────────────


def resolve_install_titan_id(install_root: Path) -> str:
    """Mirror state_registry.resolve_titan_id (data/titan_identity.json → T1)."""
    identity = install_root / "data" / "titan_identity.json"
    try:
        if identity.exists():
            tid = json.loads(identity.read_text()).get("titan_id")
            if tid:
                return str(tid)
    except (OSError, json.JSONDecodeError, ValueError):
        pass
    return "T1"


def kernel_binary(install_root: Path) -> Path:
    return install_root / "bin" / "titan-kernel-rs"


def keypair_path(install_root: Path) -> Path:
    return install_root / "data" / "titan_identity_keypair.json"


def cleanup_script(install_root: Path) -> Path:
    return install_root / "scripts" / "titan_phase_c_cleanup.sh"


def microkernel_override(titan_id: str) -> Path:
    """Per-Titan runtime override read by the kernel (wins over config.toml base)."""
    return Path.home() / ".titan" / f"microkernel_{titan_id}.toml"


def ensure_l0_rust_override(titan_id: str) -> Result:
    """Phase C: turn ON the Rust L0 compute path for this install.

    setup_titan ALWAYS provisions the Rust binaries (release assets, or
    `--build-rust`), so this is a genuine Phase C microkernel — `l0_rust_enabled`
    MUST be true. Without it the kernel boots but the L0 drivers stay dark: IQL
    reasoning never trains, and the dream/fatigue + trinity compute never run, so
    the Titan never dreams or meditates. The config.toml base default stays `false`
    (safe for a binary-less source checkout); the per-Titan override at
    ~/.titan/microkernel_<id>.toml is the authoritative on-switch and wins.

    Idempotent: flips an existing `false`, inserts under an existing
    `[microkernel]`, or creates the file — never clobbers unrelated override keys.
    """
    ov = microkernel_override(titan_id)
    ov.parent.mkdir(parents=True, exist_ok=True)
    text = ov.read_text() if ov.exists() else ""
    if re.search(r"(?m)^\s*l0_rust_enabled\s*=\s*true\b", text):
        return Result("microkernel", "ok",
                      f"{ov} → l0_rust_enabled=true (already set)")
    if re.search(r"(?m)^\s*l0_rust_enabled\s*=", text):
        text = re.sub(r"(?m)^(\s*l0_rust_enabled\s*=).*$",
                      r"\1 true", text, count=1)
    elif re.search(r"(?m)^\s*\[microkernel\]\s*$", text):
        text = re.sub(r"(?m)^(\s*\[microkernel\]\s*)$",
                      r"\1\nl0_rust_enabled = true", text, count=1)
    else:
        text = (text.rstrip() + "\n\n" if text.strip() else "") \
            + "[microkernel]\nl0_rust_enabled = true\n"
    ov.write_text(text)
    return Result("microkernel", "ok",
                  f"{ov} → l0_rust_enabled=true (Phase C L0 active)")


# ── unit rendering ──────────────────────────────────────────────────────────


def render_unit(*, install_root: Path, titan_id: str, user: str) -> str:
    """Produce the titan.service text — generalized titan-tN.service."""
    root = str(install_root)
    bin_dir = f"{root}/bin"
    venv_py = f"{root}/test_env/bin/python"
    cleanup = str(cleanup_script(install_root))
    return f"""\
# {UNIT_NAME} — Phase C Rust microkernel for Titan {titan_id}.
# Generated by setup_titan (W1.e). Generalized mirror of titan-tN.service:
# a system-level unit owned by the installing user, so it survives reboot
# without enable-linger. Edit titan_hcl/config.toml / data/ — not this file
# (re-run `setup_titan repair` to regenerate the unit).

[Unit]
Description=Titan Microkernel v2 (Phase C — Rust L0) — Titan {titan_id}
After=network.target
ConditionPathExists={keypair_path(install_root)}
# Cold boot on a constrained box (2 vCPU / 4 GB min tier) can lose the daemon→bus
# connect race: the kernel's bus broker (B4) needs a beat to bind the socket
# before the 9 daemons dial it. The kernel's own supervisor recovers, but a tight
# StartLimit would trip first and wedge the unit. Be forgiving: 10 starts / 10 min.
StartLimitIntervalSec=600
StartLimitBurst=10

[Service]
Type=simple
User={user}
WorkingDirectory={root}
EnvironmentFile=-{root}/.titan_env
Environment=MALLOC_ARENA_MAX=2
Environment=TITAN_ID={titan_id}
Environment=TITAN_ROOT={root}
Environment=TITAN_KERNEL_LOG_LEVEL=info
Environment=TITAN_DAEMON_BINARY_DIR={bin_dir}
Environment=PYTHONPATH={root}/scripts:{root}
Environment=PYTHONUNBUFFERED=1
Environment=PYTHONFAULTHANDLER=1
Environment=PYTHON={venv_py}

# Idempotent cleanup before each start (and after each stop).
ExecStartPre={cleanup}
ExecStart={bin_dir}/titan-kernel-rs --titan-id {titan_id} --data-dir {root}/data
ExecStop=/bin/kill -TERM $MAINPID
ExecStopPost={cleanup}

TimeoutStopSec=30
Restart=on-failure
# Give the bus broker room to bind its socket before daemons redial on a restart
# (longer than the 5s default to damp the cold-boot connect race on min-tier).
RestartSec=10s
RestartPreventExitStatus=2 3 4 5 6

StandardOutput=journal
StandardError=journal

[Install]
WantedBy=multi-user.target
"""


# ── sudo helper (explicit, minimal footprint) ───────────────────────────────


def _sudo(cmd: list[str], *, explain: str) -> subprocess.CompletedProcess:
    """Run a privileged command, printing exactly what runs as root first."""
    cprint(f"  [sudo] {explain}", role="warning")
    cprint(f"        $ sudo {' '.join(cmd)}", role="text_muted")
    return subprocess.run(["sudo", *cmd], text=True)


# ── health gate ─────────────────────────────────────────────────────────────


def _health_ok(port: int, timeout_s: float = 3.0) -> bool:
    try:
        with urllib.request.urlopen(f"http://127.0.0.1:{port}/health", timeout=timeout_s) as r:
            return r.status == 200
    except (urllib.error.URLError, TimeoutError, OSError):
        return False


def wait_for_health(port: int, *, deadline_s: int = HEALTH_TIMEOUT_S) -> bool:
    """Poll /health until 200 or deadline. Returns True on first 200."""
    waited = 0
    while waited < deadline_s:
        if _health_ok(port):
            return True
        time.sleep(HEALTH_INTERVAL_S)
        waited += HEALTH_INTERVAL_S
        cprint(f"  …waiting for Titan to come up ({waited}/{deadline_s}s)", role="text_muted")
    return _health_ok(port)


# ── Phase 7 body ────────────────────────────────────────────────────────────


def run_systemd_phase(state: dict, install_root: Path, mode: Mode, *,
                      default: bool, prompter=None,
                      api_port: int = DEFAULT_API_PORT) -> list[Result]:
    """Install the systemd unit, ask the user whether to start now, then (if yes)
    first-start + health-gate. The unit is ALWAYS installed by the installer — a
    normal user can't hand-roll a system-supervised service — only the *start* is
    the user's choice."""
    results: list[Result] = []
    titan_id = resolve_install_titan_id(install_root)
    user = getpass.getuser()

    binary = kernel_binary(install_root)
    if not binary.exists():
        return [Result("systemd", "fail", f"kernel binary missing: {binary}",
                       "Fetch the prebuilt Rust binaries (GitHub Release for this tag) into "
                       "bin/, or build from titan-rust/ — then re-run `setup_titan repair`.")]
    if not cleanup_script(install_root).exists():
        return [Result("systemd", "fail",
                       f"cleanup script missing: {cleanup_script(install_root)}",
                       "Re-clone the repo at the release tag (incomplete checkout).")]

    keypair = keypair_path(install_root)
    if not keypair.exists():
        results.append(Result("identity", "warn", f"no keypair at {keypair}",
                              "The unit installs but will not start until genesis runs "
                              "(re-run without --skip-genesis, or `setup_titan repair`)."))

    # Make sure the cleanup script is executable (git preserves the bit, but a
    # zip-download of the release would not).
    cleanup_script(install_root).chmod(0o755)

    # Phase C: enable the Rust L0 compute path BEFORE first start, else the kernel
    # boots with L0 dark (no IQL training, no dreams/meditation). Always-on for a
    # setup_titan install since it ships the Rust binaries.
    results.append(ensure_l0_rust_override(titan_id))

    unit_text = render_unit(install_root=install_root, titan_id=titan_id, user=user)
    cprint(f"  Installing {UNIT_NAME} (Titan {titan_id}, user {user}) → {UNIT_DEST}",
           role="text_strong")

    # Write to a user-owned temp first, then sudo-install (avoids a root-owned
    # tee heredoc; keeps the privileged surface to cp + chmod + systemctl).
    tmp = install_root / "data" / f".{UNIT_NAME}.staged"
    tmp.parent.mkdir(parents=True, exist_ok=True)
    tmp.write_text(unit_text)

    # Ask whether to start now (interactive only; --default auto-starts). The unit
    # is enabled either way (boot-start); "start now" just adds `--now`.
    start_now = True
    if prompter is not None and not default and keypair.exists():
        start_now = prompter.confirm(
            "start_titan_now", "Your Titan is ready — start it now?", default_yes=True)

    enable_step = (
        (["systemctl", "enable", "--now", UNIT_NAME], "enable (start on boot) and start Titan now")
        if start_now else
        (["systemctl", "enable", UNIT_NAME], "enable Titan to start on boot (not starting now)"))
    steps = [
        (["cp", str(tmp), str(UNIT_DEST)], f"install the unit file to {UNIT_DEST}"),
        (["chmod", "644", str(UNIT_DEST)], "set unit perms to 0644"),
        (["systemctl", "daemon-reload"], "reload systemd so it sees the new unit"),
        enable_step,
    ]
    for cmd, explain in steps:
        rc = _sudo(cmd, explain=explain).returncode
        if rc != 0:
            tmp.unlink(missing_ok=True)
            return results + [Result("systemd", "fail",
                                     f"`sudo {' '.join(cmd)}` exited {rc}",
                                     "Inspect the error above; ensure your user has sudo "
                                     "and systemd is the init system.")]
    tmp.unlink(missing_ok=True)

    if not keypair.exists():
        results.append(Result("systemd", "ok", f"{UNIT_NAME} installed + enabled (boot-start)"))
        results.append(Result("health", "warn",
                              "skipping start/health — no identity yet (unit will not start).",
                              "Run genesis, then `sudo systemctl start titan.service`."))
        return results

    if not start_now:
        results.append(Result("systemd", "ok",
                              f"{UNIT_NAME} installed + enabled (starts on boot); not started now"))
        results.append(Result("start", "warn",
                              "Titan not started (your choice) — start it anytime:",
                              f"sudo systemctl start {UNIT_NAME}"))
        return results

    results.append(Result("systemd", "ok", f"{UNIT_NAME} installed + enabled + started"))
    cprint(f"  First-start health gate — polling http://127.0.0.1:{api_port}/health "
           f"(up to {HEALTH_TIMEOUT_S}s)…", role="text_strong")
    if wait_for_health(api_port):
        results.append(Result("health", "ok", f"Titan healthy at :{api_port}/health (HTTP 200)"))
    else:
        results.append(Result("health", "fail",
                              f"no HTTP 200 from :{api_port}/health within {HEALTH_TIMEOUT_S}s",
                              "Check logs: `journalctl -u titan.service -n 100 --no-pager`."))
    return results
